// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAusecUust9OIUbLhu6lUZvl3Qjxc7gNwA',
    appId: '1:383340843863:web:3ac16897f1c5941c2e2412',
    messagingSenderId: '383340843863',
    projectId: 'todoapp-977b0',
    authDomain: 'todoapp-977b0.firebaseapp.com',
    storageBucket: 'todoapp-977b0.firebasestorage.app',
    measurementId: 'G-6JDJ1TZGPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh0ybx1RdbsuZ3H3OmtB9xjaLxnpvSfMo',
    appId: '1:383340843863:android:6a4e34ad712e54f02e2412',
    messagingSenderId: '383340843863',
    projectId: 'todoapp-977b0',
    storageBucket: 'todoapp-977b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4J2n6nIL9PulzNsMf6PuvK55UDGOApNA',
    appId: '1:383340843863:ios:288c72ca2b4b82722e2412',
    messagingSenderId: '383340843863',
    projectId: 'todoapp-977b0',
    storageBucket: 'todoapp-977b0.firebasestorage.app',
    iosClientId: '383340843863-lv0uek8l2oaojcihgp0o3a4as0c2tjh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4J2n6nIL9PulzNsMf6PuvK55UDGOApNA',
    appId: '1:383340843863:ios:288c72ca2b4b82722e2412',
    messagingSenderId: '383340843863',
    projectId: 'todoapp-977b0',
    storageBucket: 'todoapp-977b0.firebasestorage.app',
    iosClientId: '383340843863-lv0uek8l2oaojcihgp0o3a4as0c2tjh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAusecUust9OIUbLhu6lUZvl3Qjxc7gNwA',
    appId: '1:383340843863:web:15938e3525ef7f532e2412',
    messagingSenderId: '383340843863',
    projectId: 'todoapp-977b0',
    authDomain: 'todoapp-977b0.firebaseapp.com',
    storageBucket: 'todoapp-977b0.firebasestorage.app',
    measurementId: 'G-1E8ZDSSWWX',
  );
}
